package com.tns.abstraction;

public class Demo {
	public static void main(String args[])
	{
		//TODO Autogenerated method 
		//Shape sh=new Shape()
		Shape sh;
		
    sh = new Square(0.3f)	;//accessing trough implementabe class
	sh.calArea();
	sh.show();
	
	sh= new Rectangle(0.2f,0.3f);
	sh.calArea();
	sh.show();
	
	}
	}