package com.tns.Assignment;
import java.util.Scanner;
public class CommisionDemo {
public static void main (String args)
{
	//Autogenerated methods
Scanner sc=new Scanner(System.in);
String name,address;
int phone,salesAmount;
System.out.println("Read the name,address,phone,salesAmount");
name=sc.nextLine();
address=sc.nextLine();
phone=sc.nextInt();
sc.nextLine();
salesAmount=sc.nextInt();
sc.nextLine();
System.out.println("The details are" + name +  " " +address+ " " + phone+ "" +salesAmount);
Commision c=new Commision();
System.out.println(c);
c.setName(name);
c.setAddress(address);
c.setPhone(phone);
c.setSalesAmount(salesAmount);
System.out.println(c);
Commision cob=new Commision(name,address,phone,salesAmount);
System.out.println(cob);
}
}