package oops.tns.constuctor;
import java.util.Scanner;
public class CustomerDemo1 {
	public static void main(String args[])
	{
		//TODO Autogenerated method
		Scanner sc =new Scanner(System.in);
		String name,city;
		int id;
		System.out.println("read name,is,city");
		id=sc.nextInt();
		sc.nextLine();
		name=sc.nextLine();
		city=sc.nextLine();
		System.out.println("The details are "+name+""+city+""+id);
		Customer1 c=new Customer1();
		System.out.println(c);
		c.setCustomerName(name);
		c.setCustomerName(city);
		c.setCustomerId(id);
		System.out.println(c);
		Customer1 cob=new Customer1(id,city,name);
		System.out.println(cob);
	}
	

}
